export const statusCode = {
  OK: 200,
  Created: 201,
  Accepted: 202,
  NoContent: 204,
  MovedPermanently: 301,
  BadRequest: 400,
  Unauthorized: 401,
  Forbiden: 403,
  NotFound: 404,
  ServerError: 500,
};
export const statusText = {
  OK: "Success",
  Created: "Created Successfully",
  Accepted: "Accepted",
  NoContent: "No Content Available",
  BadRequest: "Bad Request",
  Unauthorized: "Unauthorized Access",
  Forbiden: "Forbiden",
  NotFound: "Not Found",
  ServerError: "Internal Server Error",
};

export const messages = {
  invalidReqBody: "Invalid request body",
  invalidCred: "Invalid Credintials",
  internalServerError: "Internal server error",
  userFound: "User found",
  errLog: "Error while logging in",
  errToken: "Error while creating token",
  userNotFound: "User not found",
  notFound: "Record not found",
  created: "User created successfully",
  createError: "Error while creating user",
  update: "Updated successfully",
  updateError: "Error while updating",
  userDeleted: "User deleted successfully",
  logedin: "Logged in Successfully",
  logout: "Logged out successfully",
  missingId: "Record ID required",
  invalidParams: "Invalid parameters",
  invalidToken: "Invalid Token",
  sww: "Something went wrong",
  successToken: "Token Created Successfully",
  userExist: "User already exits",
};
